name: CI - Pull request

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    install-dependencies:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
    lint:
        name: Linter check
        needs: [install-dependencies]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Lint
              run: npm run lint
    prettier:
        name: Formatter check
        needs: [install-dependencies]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Prettier
              run: npm run prettier
    ts-check:
        defaults:
            run:
                working-directory: './frontend'
        name: TypeScript check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: TypeScript check
              run: npm run ts-check
