name: CI - Pull request

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Linter check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install root Dependencies
              run: npm ci
            - name: Install frontend dependencies
              run: npm ci --prefix ./frontend
            - name: Lint
              run: npm run lint
    prettier:
        name: Formatter check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Prettier
              run: npm run prettier
    ts-check:
        name: TypeScript check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install root Dependencies
              run: npm ci
            - name: Install frontend dependencies
              run: npm ci --prefix ./frontend
            - name: TypeScript check
              run: npm run ts-check
